services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: matalabs-backend
    restart: unless-stopped
    ports:
      - "8085:8080"
    env_file:
      - .env
    volumes:
      - ./data:/app/data
